---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "주문"
    labels: 
      app: "주문"
  spec: 
    selector: 
      matchLabels: 
        app: "주문"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "주문"
      spec: 
        containers: 
          - 
            name: "주문"
            image: "주문"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "주문"
    labels: 
      app: "주문"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "주문"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "배송"
    labels: 
      app: "배송"
  spec: 
    selector: 
      matchLabels: 
        app: "배송"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "배송"
      spec: 
        containers: 
          - 
            name: "배송"
            image: "배송"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "배송"
    labels: 
      app: "배송"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "배송"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "결재"
    labels: 
      app: "결재"
  spec: 
    selector: 
      matchLabels: 
        app: "결재"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "결재"
      spec: 
        containers: 
          - 
            name: "결재"
            image: "결재"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "결재"
    labels: 
      app: "결재"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "결재"
